syntax = "proto3";

package dataRequest;

option java_package = "com.hiren.grpcsync";
option java_multiple_files = true;

message ChatRequest {
  int64 messageId = 1; // TimeStamp
  string senderId = 2; // Ip of Sender
  string receiverId = 3; // Ip of Receiver
  string content = 4; // Message Content
  int64 timestamp = 5; // Sent Time
  bool status = 6; // Message Status "sent"
  string type = 7; // Message type such as "EDIT", "ADD", "DELETE"
}

message ChatResponse {
  bool received = 1;
  string info = 2;
  string type = 3; // Message type such as "EDIT", "ADD", "DELETE"
}

service ChatService {
  rpc getChat(ChatRequest) returns (ChatResponse);

  // 🔥 Bi-directional streaming
  rpc StreamChat(stream ChatRequest) returns (stream ChatResponse);
}

service MessagingService {
  rpc connect(stream ChatRequest) returns (stream ChatResponse);
}